# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - master
pr:
  - master
variables:
  GO_VERSION: 1.13
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: Checks
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make checks
        env:
          GITHUB_TOKEN: $(DOCKER_PASSWORD)
        displayName: Run checks

  - job: UnitTest
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test
        displayName: Run unit test
      - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
        env:
          CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
        displayName: Upload coverage to Codecov

  - job: UnitTestWasm
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test-wasm
        displayName: Run unit test wasm

  - job: Publish
    dependsOn:
      - Checks
      - UnitTest
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          source ci/version_var.sh
          echo $DOCKER_PASSWORD | docker login docker.pkg.github.com --username $DOCKER_USER --password-stdin
          make user-agent-wasm-docker
          docker tag docker.pkg.github.com/trustbloc/edge-agent/user-agent-wasm:latest docker.pkg.github.com/trustbloc/edge-agent/user-agent-wasm:$EDGE_AGENT_TAG
          docker push docker.pkg.github.com/trustbloc/edge-agent/user-agent-wasm:$EDGE_AGENT_TAG
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
          GITHUB_TOKEN: $(DOCKER_PASSWORD)
